services:
  - type: web
    name: meu-portfolio
    runtime: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "18"
    plan: free
